FROM node:20-alpine

# Install OS dependencies needed for bcrypt and others
RUN apk add --no-cache python3 make g++ && npm install -g ts-node-dev

WORKDIR /app

# Install dependencies (including devDependencies)
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Use ts-node-dev to enable hot reload
CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
