import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateAuditColumnNaming1746801370704 implements MigrationInterface {
    name = 'UpdateAuditColumnNaming1746801370704'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_d6e163bd2cfdd79045d0a95d94d"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_ed73e18ffea3c5e2699a5b3b192"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP CONSTRAINT "FK_5f5bd51e887ab3fe5f828f262e2"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP CONSTRAINT "FK_d95287b24bfc53adec4272138a2"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_49788ff70c36810872a550ccae0"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_f9a7a611606954b809b9937c2f7"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_82319f64187836b307e6d6ba08d"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_a19025a009be58684a63961aaf3"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP CONSTRAINT "FK_c077cf7d4ed3dd115eeffaf87fe"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP CONSTRAINT "FK_fadcf10ed6264ff6100b80a2d02"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_bb6e4d306c019df594a6ac8444b"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_baab1b94636ef6abdf024dd2ef5"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_2a142cd65f2cffe2d70de14ff36"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_fa6a675e30b3b9e71a9388bf288"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_345801c2d250d9eb1d27e0099b9"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_47c50b09a30fdbbc3f9e2f2cbf4"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "order" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_d348286667373cbcec5463cda5b" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_b0c596f429ff2966d03516ef1ca" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD CONSTRAINT "FK_77d50c758c061e736fa25300021" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD CONSTRAINT "FK_036f35eb750795aea9caf60e703" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_40cacb6be0d8e432209d2582bf3" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_af45584d82c11bc28e1a64b0c94" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d2f5e343630bd8b7e1e7534e82e" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_6bfae5ab9f39212d5b6ad0276b1" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD CONSTRAINT "FK_c9ad67e5fd9023a35ca10dbe192" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD CONSTRAINT "FK_8fd063c573ae638129b2b12c692" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_e0cb582def87a5f8e4336453363" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_9581f923675dbf9572062e3e002" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_ed947f1c5c1282f6fd4405ffd87" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_af818664e8ef7a22906a90919f8" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_130f9abd1e8cdafc35e18caa45c" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_a3ee82f470d1f484a4bf2beab39" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_a3ee82f470d1f484a4bf2beab39"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_130f9abd1e8cdafc35e18caa45c"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_af818664e8ef7a22906a90919f8"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_ed947f1c5c1282f6fd4405ffd87"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_9581f923675dbf9572062e3e002"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_e0cb582def87a5f8e4336453363"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP CONSTRAINT "FK_8fd063c573ae638129b2b12c692"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP CONSTRAINT "FK_c9ad67e5fd9023a35ca10dbe192"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_6bfae5ab9f39212d5b6ad0276b1"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d2f5e343630bd8b7e1e7534e82e"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_af45584d82c11bc28e1a64b0c94"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_40cacb6be0d8e432209d2582bf3"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP CONSTRAINT "FK_036f35eb750795aea9caf60e703"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP CONSTRAINT "FK_77d50c758c061e736fa25300021"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_b0c596f429ff2966d03516ef1ca"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_d348286667373cbcec5463cda5b"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "menu_category" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "order" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_47c50b09a30fdbbc3f9e2f2cbf4" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_345801c2d250d9eb1d27e0099b9" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_fa6a675e30b3b9e71a9388bf288" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_2a142cd65f2cffe2d70de14ff36" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_baab1b94636ef6abdf024dd2ef5" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_bb6e4d306c019df594a6ac8444b" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD CONSTRAINT "FK_fadcf10ed6264ff6100b80a2d02" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_category" ADD CONSTRAINT "FK_c077cf7d4ed3dd115eeffaf87fe" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_a19025a009be58684a63961aaf3" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_82319f64187836b307e6d6ba08d" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_f9a7a611606954b809b9937c2f7" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_49788ff70c36810872a550ccae0" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD CONSTRAINT "FK_d95287b24bfc53adec4272138a2" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_table" ADD CONSTRAINT "FK_5f5bd51e887ab3fe5f828f262e2" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_ed73e18ffea3c5e2699a5b3b192" FOREIGN KEY ("updatedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_d6e163bd2cfdd79045d0a95d94d" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
